# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
header:
  title: "Kseniia Sheremet"
  telegram: "https://www.facebook.com/ramswaroop"
  facebook: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
footer:
  name: "Hey there, my name is Ram"
  bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
  github: 'Want a website like this for yourself for free? Just <a href="https://github.com/ramswaroop/photography">fork me on github</a> ;)'
web_design: "AJ"
about:
  title: "Hey, I'm Kseniia and let me introduce myself"
  text:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
price:
  card-1:
    title: "card-1"
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
    time: "4 hours"
    price: "150"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
