# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
header:
  title: "Kseniia Sheremet"
footer:
  name: "Hey there, my name is Ram"
  bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
  github: 'Want a website like this for yourself for free? Just <a href="https://github.com/ramswaroop/photography">fork me on github</a> ;)'
social:
  telegram: "https://www.facebook.com/"
  facebook: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
about:
  title: "Hey, I'm Kseniia and let me introduce myself"
  text:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
price:
  card1:
    title: "Family Photoset"
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
    time: "4 hours"
    price: "150"
  card2:
    title: "Black and white Photoset"
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
    time: "10 hours"
    price: "350"
  card3:
    title: "Commercial Photoset"
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit repellat alias placeat nostrum eos odio, dolores natus quibusdam tempora corporis temporibus suscipit provident exercitationem nam facilis eaque vitae deleniti esse."
    time: "12 hours"
    price: "600"
contact:
  title: "Hello, I'am Kseniia Sheremet"
  subtitle: "Proffesional photographer"
# faq:
#   question:
#     title: "First question"
#     answer: "<strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow."
#   question:
#     title: "Second question"
#     answer: "<strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow."
#   question:
#     title: "Third question"
#     answer: "<strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow."
